[package]
name = "stt-local"
version = "0.1.0"
edition = "2021"

[dependencies]
stt-core = { path = "../core" }
async-trait = "0.1"
anyhow = "1.0"
whisper-rs = { version = "0.13.2", features = ["openblas"] }
hound = "3.5.1"
tokio = { version = "1", features = ["full"] }
